/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "wrapper.go"

#include <stdlib.h>
#include <string.h>

typedef struct {
    char* endpoint;
    char* access_key_id;
    char* secret_access_key;
    char* bucket_name;
    char* region;
    char* password;
    char* prefix;
    int connections;
    int use_http;
} ResticConfig;

typedef struct {
    char* snapshot_id;
    char* time;
    char* hostname;
    int path_count;
    char** paths;
    int tag_count;
    char** tags;
} ResticSnapshot;

typedef struct {
    char* error_message;
} ResticError;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern ResticError* ResticInitRepository(ResticConfig* cfg);
extern int ResticNewClient(ResticConfig* cfg);
extern void ResticCloseClient(int clientID);
extern char* ResticBackup(int clientID, char** paths, int pathCount, char** tags, int tagCount, char* hostname);
extern ResticError* ResticRestore(int clientID, char* snapshotID, char* target);
extern ResticSnapshot** ResticListSnapshots(int clientID, int* count);
extern void ResticFreeSnapshots(ResticSnapshot** snapshots, int count);
extern void ResticFreeError(ResticError* err);
extern void ResticFreeString(char* str);

#ifdef __cplusplus
}
#endif
